Menu:
  Home: /
  Archives: /archives/
  About: /about/
  # Category: /category_archive
  Tag: /tags/
  Github: https://github.com/linfeizheng/
  RSS: /atom.xml
  Search: false
  
Site:
  Motto: 郑林飞的个人网站

Intro:
  Avastar: img/avastar.jpeg
  Name: Sōsuke
  Brief: aimed in front-end 
  SNS: 
    Weibo:  
    StackOverflow: 
    Github: https://github.com/Vevlins
    Pinterest: 
    Quora: 

CopyRight: 
  Author: 郑林飞
  License: ""

Tip:
  Alipay: /img/qrcode.jpeg
  Wechat: /img/qrcode.jpeg

Comment:
  Id: 8d83609a651e972e308d
  Secret: 37e40c89a47e957f654e86f71c5caaccad0774de
  Repo: Vevlins.github.io
  Owner: Vevlins